PRAGMA foreign_keys = ON;

-- Migration 0004: Cau truc lo trinh hoc CEFR A1-C1 (levels -> units -> vocabulary + sentences)
-- Noi dung do Claude (Anthropic) bien soan truc tiep, nguyen goc, khong sao chep tu sach/khoa hoc nao.
-- Khong xoa/doi bang content_topics/content_phrases cu de khong pha vo API dang chay.

CREATE TABLE content_levels (
  id TEXT PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  level_order INTEGER NOT NULL
);

CREATE TABLE content_units (
  id TEXT PRIMARY KEY,
  level_id TEXT NOT NULL REFERENCES content_levels(id),
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  icon TEXT NOT NULL,
  target_persona TEXT NOT NULL,
  unit_order INTEGER NOT NULL
);

CREATE TABLE content_level_vocabulary (
  id TEXT PRIMARY KEY,
  unit_id TEXT NOT NULL REFERENCES content_units(id),
  word TEXT NOT NULL,
  ipa TEXT,
  meaning_vi TEXT NOT NULL,
  example_en TEXT NOT NULL,
  example_vi TEXT NOT NULL,
  word_order INTEGER NOT NULL
);

CREATE TABLE content_unit_sentences (
  id TEXT PRIMARY KEY,
  unit_id TEXT NOT NULL REFERENCES content_units(id),
  english TEXT NOT NULL,
  vietnamese_hint TEXT NOT NULL,
  audio_tip TEXT,
  focus_grammar TEXT,
  sentence_order INTEGER NOT NULL
);

CREATE INDEX idx_units_level ON content_units(level_id, unit_order);
CREATE INDEX idx_level_vocab_unit ON content_level_vocabulary(unit_id, word_order);
CREATE INDEX idx_unit_sentences_unit ON content_unit_sentences(unit_id, sentence_order);

INSERT INTO content_levels (id, code, title, description, level_order) VALUES
  ('lvl_a1', 'A1', 'Người mới bắt đầu', 'Nền tảng giao tiếp cơ bản: chào hỏi, sinh hoạt hàng ngày, gia đình.', 1),
  ('lvl_a2', 'A2', 'Sơ cấp', 'Giao tiếp trong các tình huống thực tế thường gặp: mua sắm, ăn uống, hỏi đường.', 2),
  ('lvl_b1', 'B1', 'Trung cấp', 'Diễn đạt ý kiến và xử lý tình huống công việc, sức khỏe, du lịch.', 3),
  ('lvl_b2', 'B2', 'Trên trung cấp', 'Tranh luận, trình bày quan điểm về công nghệ và xã hội.', 4),
  ('lvl_c1', 'C1', 'Nâng cao', 'Giao tiếp học thuật, kinh doanh và diễn đạt tinh tế như người bản xứ.', 5);

INSERT INTO content_units (id, level_id, title, description, icon, target_persona, unit_order) VALUES
  ('unit_a1_1', 'lvl_a1', 'Chào hỏi & Giới thiệu bản thân', 'Học cách chào hỏi và giới thiệu bản thân bằng tiếng Anh.', '👋', 'conversation_partner', 1),
  ('unit_a1_2', 'lvl_a1', 'Số đếm, Thời gian & Sinh hoạt hàng ngày', 'Nói về giờ giấc và các hoạt động thường ngày.', '⏰', 'conversation_partner', 2),
  ('unit_a1_3', 'lvl_a1', 'Gia đình & Thông tin cá nhân', 'Giới thiệu về gia đình và thông tin cá nhân cơ bản.', '👨‍👩‍👧', 'conversation_partner', 3),
  ('unit_a2_1', 'lvl_a2', 'Mua sắm & Tiền bạc', 'Từ vựng và mẫu câu dùng khi mua sắm, hỏi giá, trả tiền.', '🛍️', 'conversation_partner', 1),
  ('unit_a2_2', 'lvl_a2', 'Ẩm thực & Nhà hàng', 'Gọi món, đặt bàn và trò chuyện tại nhà hàng.', '🍽️', 'conversation_partner', 2),
  ('unit_a2_3', 'lvl_a2', 'Đường đi & Địa điểm', 'Hỏi đường, chỉ đường và mô tả vị trí.', '🗺️', 'conversation_partner', 3),
  ('unit_b1_1', 'lvl_b1', 'Công việc & Học tập', 'Trao đổi về công việc, deadline, kỹ năng và kinh nghiệm.', '💼', 'fluency_coach', 1),
  ('unit_b1_2', 'lvl_b1', 'Sức khỏe & Cơ thể', 'Mô tả triệu chứng, đặt lịch khám và nói về sức khỏe.', '🏥', 'grammar_tutor', 2),
  ('unit_b1_3', 'lvl_b1', 'Du lịch & Phương tiện', 'Xử lý tình huống ở sân bay, ga tàu và đặt chỗ ở.', '✈️', 'fluency_coach', 3),
  ('unit_b2_1', 'lvl_b2', 'Quan điểm & Tranh luận', 'Trình bày và bảo vệ quan điểm cá nhân một cách thuyết phục.', '💬', 'fluency_coach', 1),
  ('unit_b2_2', 'lvl_b2', 'Công nghệ & Truyền thông', 'Thảo luận về AI, quyền riêng tư và an ninh mạng.', '💻', 'fluency_coach', 2),
  ('unit_b2_3', 'lvl_b2', 'Môi trường & Xã hội', 'Bàn luận về phát triển bền vững và các vấn đề xã hội.', '🌍', 'fluency_coach', 3),
  ('unit_c1_1', 'lvl_c1', 'Kinh doanh & Đàm phán', 'Ngôn ngữ đàm phán, thương lượng và họp hành chuyên nghiệp.', '🤝', 'fluency_coach', 1),
  ('unit_c1_2', 'lvl_c1', 'Thảo luận học thuật', 'Từ vựng học thuật dùng trong nghiên cứu và tranh biện.', '🎓', 'grammar_tutor', 2),
  ('unit_c1_3', 'lvl_c1', 'Thành ngữ & Diễn đạt tinh tế', 'Thành ngữ tự nhiên giúp nói tiếng Anh như người bản xứ.', '✨', 'fluency_coach', 3);

INSERT INTO content_level_vocabulary (id, unit_id, word, ipa, meaning_vi, example_en, example_vi, word_order) VALUES
  ('vocab_unit_a1_1_1', 'unit_a1_1', 'hello', '/həˈloʊ/', 'xin chào', 'Hello, how are you?', 'Xin chào, bạn khỏe không?', 1),
  ('vocab_unit_a1_1_2', 'unit_a1_1', 'name', '/neɪm/', 'tên', 'My name is Lan.', 'Tên tôi là Lan.', 2),
  ('vocab_unit_a1_1_3', 'unit_a1_1', 'nice', '/naɪs/', 'vui, tốt đẹp', 'Nice to meet you.', 'Rất vui được gặp bạn.', 3),
  ('vocab_unit_a1_1_4', 'unit_a1_1', 'from', '/frʌm/', 'đến từ', 'I''m from Vietnam.', 'Tôi đến từ Việt Nam.', 4),
  ('vocab_unit_a1_1_5', 'unit_a1_1', 'old', '/oʊld/', 'tuổi', 'I am twenty years old.', 'Tôi hai mươi tuổi.', 5),
  ('vocab_unit_a1_1_6', 'unit_a1_1', 'work', '/wɜːrk/', 'công việc, làm việc', 'I work in an office.', 'Tôi làm việc trong văn phòng.', 6),
  ('vocab_unit_a1_1_7', 'unit_a1_1', 'student', '/ˈstuːdənt/', 'học sinh, sinh viên', 'She is a student.', 'Cô ấy là sinh viên.', 7),
  ('vocab_unit_a1_1_8', 'unit_a1_1', 'friend', '/frend/', 'bạn bè', 'He is my friend.', 'Anh ấy là bạn của tôi.', 8),
  ('vocab_unit_a1_2_1', 'unit_a1_2', 'morning', '/ˈmɔːrnɪŋ/', 'buổi sáng', 'I wake up in the morning.', 'Tôi thức dậy vào buổi sáng.', 1),
  ('vocab_unit_a1_2_2', 'unit_a1_2', 'breakfast', '/ˈbrekfəst/', 'bữa sáng', 'I eat breakfast at seven.', 'Tôi ăn sáng lúc bảy giờ.', 2),
  ('vocab_unit_a1_2_3', 'unit_a1_2', 'school', '/skuːl/', 'trường học', 'I go to school every day.', 'Tôi đi học mỗi ngày.', 3),
  ('vocab_unit_a1_2_4', 'unit_a1_2', 'evening', '/ˈiːvnɪŋ/', 'buổi tối', 'I watch TV in the evening.', 'Tôi xem TV vào buổi tối.', 4),
  ('vocab_unit_a1_2_5', 'unit_a1_2', 'sleep', '/sliːp/', 'ngủ', 'I sleep at ten o''clock.', 'Tôi ngủ lúc mười giờ.', 5),
  ('vocab_unit_a1_2_6', 'unit_a1_2', 'always', '/ˈɔːlweɪz/', 'luôn luôn', 'I always brush my teeth.', 'Tôi luôn đánh răng.', 6),
  ('vocab_unit_a1_2_7', 'unit_a1_2', 'never', '/ˈnevər/', 'không bao giờ', 'I never skip breakfast.', 'Tôi không bao giờ bỏ bữa sáng.', 7),
  ('vocab_unit_a1_2_8', 'unit_a1_2', 'o''clock', '/əˈklɒk/', 'giờ (chỉ giờ tròn)', 'It is seven o''clock.', 'Bây giờ là bảy giờ.', 8),
  ('vocab_unit_a1_3_1', 'unit_a1_3', 'mother', '/ˈmʌðər/', 'mẹ', 'My mother is a teacher.', 'Mẹ tôi là giáo viên.', 1),
  ('vocab_unit_a1_3_2', 'unit_a1_3', 'father', '/ˈfɑːðər/', 'bố', 'My father works at a bank.', 'Bố tôi làm việc ở ngân hàng.', 2),
  ('vocab_unit_a1_3_3', 'unit_a1_3', 'sister', '/ˈsɪstər/', 'chị/em gái', 'I have one sister.', 'Tôi có một chị/em gái.', 3),
  ('vocab_unit_a1_3_4', 'unit_a1_3', 'brother', '/ˈbrʌðər/', 'anh/em trai', 'My brother is ten years old.', 'Anh/em trai tôi mười tuổi.', 4),
  ('vocab_unit_a1_3_5', 'unit_a1_3', 'family', '/ˈfæməli/', 'gia đình', 'I love my family.', 'Tôi yêu gia đình mình.', 5),
  ('vocab_unit_a1_3_6', 'unit_a1_3', 'address', '/əˈdres/', 'địa chỉ', 'What is your address?', 'Địa chỉ của bạn là gì?', 6),
  ('vocab_unit_a1_3_7', 'unit_a1_3', 'phone number', '/foʊn ˈnʌmbər/', 'số điện thoại', 'Can I have your phone number?', 'Cho tôi xin số điện thoại được không?', 7),
  ('vocab_unit_a1_3_8', 'unit_a1_3', 'married', '/ˈmærid/', 'đã kết hôn', 'My sister is married.', 'Chị tôi đã kết hôn.', 8),
  ('vocab_unit_a2_1_1', 'unit_a2_1', 'price', '/praɪs/', 'giá cả', 'What is the price of this shirt?', 'Giá của cái áo này là bao nhiêu?', 1),
  ('vocab_unit_a2_1_2', 'unit_a2_1', 'expensive', '/ɪkˈspensɪv/', 'đắt', 'This bag is too expensive.', 'Cái túi này quá đắt.', 2),
  ('vocab_unit_a2_1_3', 'unit_a2_1', 'cheap', '/tʃiːp/', 'rẻ', 'I want something cheap.', 'Tôi muốn thứ gì đó rẻ hơn.', 3),
  ('vocab_unit_a2_1_4', 'unit_a2_1', 'discount', '/ˈdɪskaʊnt/', 'giảm giá', 'Is there a discount today?', 'Hôm nay có giảm giá không?', 4),
  ('vocab_unit_a2_1_5', 'unit_a2_1', 'cash', '/kæʃ/', 'tiền mặt', 'I will pay in cash.', 'Tôi sẽ trả bằng tiền mặt.', 5),
  ('vocab_unit_a2_1_6', 'unit_a2_1', 'receipt', '/rɪˈsiːt/', 'hóa đơn', 'Can I have the receipt?', 'Cho tôi xin hóa đơn được không?', 6),
  ('vocab_unit_a2_1_7', 'unit_a2_1', 'size', '/saɪz/', 'kích cỡ', 'Do you have a bigger size?', 'Bạn có cỡ lớn hơn không?', 7),
  ('vocab_unit_a2_1_8', 'unit_a2_1', 'try on', '/traɪ ɒn/', 'thử (quần áo)', 'Can I try this on?', 'Tôi thử cái này được không?', 8),
  ('vocab_unit_a2_2_1', 'unit_a2_2', 'menu', '/ˈmenjuː/', 'thực đơn', 'Can I see the menu?', 'Cho tôi xem thực đơn được không?', 1),
  ('vocab_unit_a2_2_2', 'unit_a2_2', 'order', '/ˈɔːrdər/', 'gọi món, đặt hàng', 'I''d like to order now.', 'Tôi muốn gọi món bây giờ.', 2),
  ('vocab_unit_a2_2_3', 'unit_a2_2', 'delicious', '/dɪˈlɪʃəs/', 'ngon', 'This soup is delicious.', 'Món súp này ngon.', 3),
  ('vocab_unit_a2_2_4', 'unit_a2_2', 'spicy', '/ˈspaɪsi/', 'cay', 'Is this dish spicy?', 'Món này có cay không?', 4),
  ('vocab_unit_a2_2_5', 'unit_a2_2', 'bill', '/bɪl/', 'hóa đơn (nhà hàng)', 'Can we have the bill, please?', 'Cho chúng tôi xin hóa đơn được không?', 5),
  ('vocab_unit_a2_2_6', 'unit_a2_2', 'reservation', '/ˌrezərˈveɪʃən/', 'đặt bàn, đặt chỗ', 'I have a reservation for two.', 'Tôi đã đặt bàn cho hai người.', 6),
  ('vocab_unit_a2_2_7', 'unit_a2_2', 'waiter', '/ˈweɪtər/', 'phục vụ nam', 'The waiter recommended this dish.', 'Người phục vụ đã gợi ý món này.', 7),
  ('vocab_unit_a2_2_8', 'unit_a2_2', 'allergic', '/əˈlɜːrdʒɪk/', 'dị ứng', 'I''m allergic to peanuts.', 'Tôi bị dị ứng với đậu phộng.', 8),
  ('vocab_unit_a2_3_1', 'unit_a2_3', 'turn', '/tɜːrn/', 'rẽ', 'Turn left at the corner.', 'Rẽ trái ở góc đường.', 1),
  ('vocab_unit_a2_3_2', 'unit_a2_3', 'straight', '/streɪt/', 'thẳng', 'Go straight ahead.', 'Đi thẳng về phía trước.', 2),
  ('vocab_unit_a2_3_3', 'unit_a2_3', 'corner', '/ˈkɔːrnər/', 'góc đường', 'The bank is on the corner.', 'Ngân hàng ở góc đường.', 3),
  ('vocab_unit_a2_3_4', 'unit_a2_3', 'near', '/nɪr/', 'gần', 'The station is near here.', 'Nhà ga ở gần đây.', 4),
  ('vocab_unit_a2_3_5', 'unit_a2_3', 'far', '/fɑːr/', 'xa', 'Is it far from here?', 'Có xa từ đây không?', 5),
  ('vocab_unit_a2_3_6', 'unit_a2_3', 'crosswalk', '/ˈkrɔːswɔːk/', 'vạch qua đường', 'Use the crosswalk to cross.', 'Dùng vạch qua đường để sang đường.', 6),
  ('vocab_unit_a2_3_7', 'unit_a2_3', 'map', '/mæp/', 'bản đồ', 'Can you show me on the map?', 'Bạn chỉ giúp tôi trên bản đồ được không?', 7),
  ('vocab_unit_a2_3_8', 'unit_a2_3', 'lost', '/lɒst/', 'lạc đường', 'I think I''m lost.', 'Tôi nghĩ tôi bị lạc đường rồi.', 8),
  ('vocab_unit_b1_1_1', 'unit_b1_1', 'deadline', '/ˈdedlaɪn/', 'hạn chót', 'The deadline is next Friday.', 'Hạn chót là thứ Sáu tới.', 1),
  ('vocab_unit_b1_1_2', 'unit_b1_1', 'colleague', '/ˈkɒliːɡ/', 'đồng nghiệp', 'My colleague helped me with the report.', 'Đồng nghiệp của tôi đã giúp tôi làm báo cáo.', 2),
  ('vocab_unit_b1_1_3', 'unit_b1_1', 'meeting', '/ˈmiːtɪŋ/', 'cuộc họp', 'We have a meeting at ten.', 'Chúng tôi có một cuộc họp lúc mười giờ.', 3),
  ('vocab_unit_b1_1_4', 'unit_b1_1', 'promotion', '/prəˈmoʊʃən/', 'thăng chức', 'She got a promotion last month.', 'Cô ấy được thăng chức tháng trước.', 4),
  ('vocab_unit_b1_1_5', 'unit_b1_1', 'resign', '/rɪˈzaɪn/', 'từ chức, nghỉ việc', 'He decided to resign from his job.', 'Anh ấy quyết định nghỉ việc.', 5),
  ('vocab_unit_b1_1_6', 'unit_b1_1', 'assignment', '/əˈsaɪnmənt/', 'nhiệm vụ, bài tập lớn', 'I need to finish this assignment tonight.', 'Tôi cần hoàn thành bài tập này tối nay.', 6),
  ('vocab_unit_b1_1_7', 'unit_b1_1', 'skill', '/skɪl/', 'kỹ năng', 'Communication is an important skill.', 'Giao tiếp là một kỹ năng quan trọng.', 7),
  ('vocab_unit_b1_1_8', 'unit_b1_1', 'experience', '/ɪkˈspɪriəns/', 'kinh nghiệm', 'She has five years of experience.', 'Cô ấy có năm năm kinh nghiệm.', 8),
  ('vocab_unit_b1_2_1', 'unit_b1_2', 'symptom', '/ˈsɪmptəm/', 'triệu chứng', 'What are your symptoms?', 'Triệu chứng của bạn là gì?', 1),
  ('vocab_unit_b1_2_2', 'unit_b1_2', 'headache', '/ˈhedeɪk/', 'đau đầu', 'I have a terrible headache.', 'Tôi bị đau đầu dữ dội.', 2),
  ('vocab_unit_b1_2_3', 'unit_b1_2', 'prescription', '/prɪˈskrɪpʃən/', 'đơn thuốc', 'The doctor gave me a prescription.', 'Bác sĩ đã kê đơn thuốc cho tôi.', 3),
  ('vocab_unit_b1_2_4', 'unit_b1_2', 'exercise', '/ˈeksərsaɪz/', 'tập thể dục', 'I exercise three times a week.', 'Tôi tập thể dục ba lần một tuần.', 4),
  ('vocab_unit_b1_2_5', 'unit_b1_2', 'diet', '/ˈdaɪət/', 'chế độ ăn', 'She is on a healthy diet.', 'Cô ấy đang theo một chế độ ăn lành mạnh.', 5),
  ('vocab_unit_b1_2_6', 'unit_b1_2', 'injury', '/ˈɪndʒəri/', 'chấn thương', 'He had a serious injury last year.', 'Anh ấy đã bị chấn thương nặng năm ngoái.', 6),
  ('vocab_unit_b1_2_7', 'unit_b1_2', 'recover', '/rɪˈkʌvər/', 'hồi phục', 'It took two weeks to recover.', 'Phải mất hai tuần để hồi phục.', 7),
  ('vocab_unit_b1_2_8', 'unit_b1_2', 'appointment', '/əˈpɔɪntmənt/', 'cuộc hẹn khám', 'I have a doctor''s appointment tomorrow.', 'Tôi có hẹn khám bác sĩ vào ngày mai.', 8),
  ('vocab_unit_b1_3_1', 'unit_b1_3', 'itinerary', '/aɪˈtɪnərəri/', 'lịch trình', 'Here is our travel itinerary.', 'Đây là lịch trình du lịch của chúng tôi.', 1),
  ('vocab_unit_b1_3_2', 'unit_b1_3', 'delay', '/dɪˈleɪ/', 'trì hoãn, hoãn', 'Our flight was delayed by two hours.', 'Chuyến bay của chúng tôi bị hoãn hai tiếng.', 2),
  ('vocab_unit_b1_3_3', 'unit_b1_3', 'luggage', '/ˈlʌɡɪdʒ/', 'hành lý', 'I need to check my luggage.', 'Tôi cần ký gửi hành lý.', 3),
  ('vocab_unit_b1_3_4', 'unit_b1_3', 'boarding pass', '/ˈbɔːrdɪŋ pæs/', 'thẻ lên máy bay', 'Please show your boarding pass.', 'Vui lòng xuất trình thẻ lên máy bay.', 4),
  ('vocab_unit_b1_3_5', 'unit_b1_3', 'destination', '/ˌdestɪˈneɪʃən/', 'điểm đến', 'Our final destination is Da Nang.', 'Điểm đến cuối cùng của chúng tôi là Đà Nẵng.', 5),
  ('vocab_unit_b1_3_6', 'unit_b1_3', 'accommodation', '/əˌkɒməˈdeɪʃən/', 'chỗ ở', 'We booked our accommodation online.', 'Chúng tôi đã đặt chỗ ở trực tuyến.', 6),
  ('vocab_unit_b1_3_7', 'unit_b1_3', 'platform', '/ˈplætfɔːrm/', 'sân ga', 'The train leaves from platform four.', 'Tàu khởi hành từ sân ga số bốn.', 7),
  ('vocab_unit_b1_3_8', 'unit_b1_3', 'transfer', '/trænsˈfɜːr/', 'chuyển tuyến, đổi chuyến', 'You need to transfer at the next station.', 'Bạn cần chuyển tuyến ở ga tiếp theo.', 8),
  ('vocab_unit_b2_1_1', 'unit_b2_1', 'argue', '/ˈɑːrɡjuː/', 'tranh luận, lập luận', 'She argued that the policy was unfair.', 'Cô ấy lập luận rằng chính sách đó không công bằng.', 1),
  ('vocab_unit_b2_1_2', 'unit_b2_1', 'controversial', '/ˌkɒntrəˈvɜːrʃəl/', 'gây tranh cãi', 'This is a controversial topic.', 'Đây là một chủ đề gây tranh cãi.', 2),
  ('vocab_unit_b2_1_3', 'unit_b2_1', 'evidence', '/ˈevɪdəns/', 'bằng chứng', 'There is no evidence to support this claim.', 'Không có bằng chứng để ủng hộ tuyên bố này.', 3),
  ('vocab_unit_b2_1_4', 'unit_b2_1', 'perspective', '/pərˈspektɪv/', 'quan điểm, góc nhìn', 'Let''s look at this from another perspective.', 'Hãy nhìn vấn đề này từ một góc nhìn khác.', 4),
  ('vocab_unit_b2_1_5', 'unit_b2_1', 'compromise', '/ˈkɒmprəmaɪz/', 'thỏa hiệp', 'We need to find a compromise.', 'Chúng ta cần tìm một sự thỏa hiệp.', 5),
  ('vocab_unit_b2_1_6', 'unit_b2_1', 'justify', '/ˈdʒʌstɪfaɪ/', 'biện minh', 'Can you justify that decision?', 'Bạn có thể biện minh cho quyết định đó không?', 6),
  ('vocab_unit_b2_1_7', 'unit_b2_1', 'objective', '/əbˈdʒektɪv/', 'khách quan', 'Try to stay objective when judging.', 'Hãy cố gắng khách quan khi đánh giá.', 7),
  ('vocab_unit_b2_1_8', 'unit_b2_1', 'bias', '/ˈbaɪəs/', 'thiên kiến, thành kiến', 'The report shows some bias.', 'Bản báo cáo cho thấy một số thiên kiến.', 8),
  ('vocab_unit_b2_2_1', 'unit_b2_2', 'innovation', '/ˌɪnəˈveɪʃən/', 'sự đổi mới', 'This company is known for innovation.', 'Công ty này nổi tiếng vì sự đổi mới.', 1),
  ('vocab_unit_b2_2_2', 'unit_b2_2', 'artificial intelligence', '/ˌɑːrtɪˈfɪʃəl ɪnˈtelɪdʒəns/', 'trí tuệ nhân tạo', 'Artificial intelligence is changing many industries.', 'Trí tuệ nhân tạo đang thay đổi nhiều ngành công nghiệp.', 2),
  ('vocab_unit_b2_2_3', 'unit_b2_2', 'privacy', '/ˈpraɪvəsi/', 'quyền riêng tư', 'People are worried about online privacy.', 'Mọi người lo lắng về quyền riêng tư trực tuyến.', 3),
  ('vocab_unit_b2_2_4', 'unit_b2_2', 'platform', '/ˈplætfɔːrm/', 'nền tảng công nghệ', 'This app runs on multiple platforms.', 'Ứng dụng này chạy trên nhiều nền tảng.', 4),
  ('vocab_unit_b2_2_5', 'unit_b2_2', 'algorithm', '/ˈælɡərɪðəm/', 'thuật toán', 'The algorithm recommends videos based on your history.', 'Thuật toán gợi ý video dựa trên lịch sử của bạn.', 5),
  ('vocab_unit_b2_2_6', 'unit_b2_2', 'cybersecurity', '/ˈsaɪbərsɪˌkjʊrəti/', 'an ninh mạng', 'Cybersecurity is a growing concern.', 'An ninh mạng là một mối lo ngày càng lớn.', 6),
  ('vocab_unit_b2_2_7', 'unit_b2_2', 'misinformation', '/ˌmɪsɪnfərˈmeɪʃən/', 'thông tin sai lệch', 'Misinformation spreads quickly online.', 'Thông tin sai lệch lan truyền nhanh trên mạng.', 7),
  ('vocab_unit_b2_2_8', 'unit_b2_2', 'dependent', '/dɪˈpendənt/', 'phụ thuộc', 'We''ve become very dependent on technology.', 'Chúng ta đã trở nên rất phụ thuộc vào công nghệ.', 8),
  ('vocab_unit_b2_3_1', 'unit_b2_3', 'sustainable', '/səˈsteɪnəbəl/', 'bền vững', 'We need more sustainable solutions.', 'Chúng ta cần nhiều giải pháp bền vững hơn.', 1),
  ('vocab_unit_b2_3_2', 'unit_b2_3', 'pollution', '/pəˈluːʃən/', 'ô nhiễm', 'Air pollution is a serious problem in big cities.', 'Ô nhiễm không khí là vấn đề nghiêm trọng ở các thành phố lớn.', 2),
  ('vocab_unit_b2_3_3', 'unit_b2_3', 'renewable', '/rɪˈnuːəbəl/', 'có thể tái tạo', 'Solar power is a renewable energy source.', 'Năng lượng mặt trời là nguồn năng lượng tái tạo.', 3),
  ('vocab_unit_b2_3_4', 'unit_b2_3', 'inequality', '/ˌɪnɪˈkwɒləti/', 'sự bất bình đẳng', 'Income inequality is rising worldwide.', 'Bất bình đẳng thu nhập đang gia tăng trên toàn thế giới.', 4),
  ('vocab_unit_b2_3_5', 'unit_b2_3', 'community', '/kəˈmjuːnəti/', 'cộng đồng', 'Our community organized a cleanup event.', 'Cộng đồng chúng tôi đã tổ chức một sự kiện dọn dẹp.', 5),
  ('vocab_unit_b2_3_6', 'unit_b2_3', 'policy', '/ˈpɒləsi/', 'chính sách', 'The government introduced a new policy.', 'Chính phủ đã đưa ra một chính sách mới.', 6),
  ('vocab_unit_b2_3_7', 'unit_b2_3', 'awareness', '/əˈweərnəs/', 'nhận thức', 'We need to raise awareness about climate change.', 'Chúng ta cần nâng cao nhận thức về biến đổi khí hậu.', 7),
  ('vocab_unit_b2_3_8', 'unit_b2_3', 'impact', '/ˈɪmpækt/', 'tác động', 'Plastic waste has a huge impact on oceans.', 'Rác thải nhựa có tác động rất lớn đến đại dương.', 8),
  ('vocab_unit_c1_1_1', 'unit_c1_1', 'negotiate', '/nɪˈɡoʊʃieɪt/', 'đàm phán', 'We need to negotiate better terms.', 'Chúng tôi cần đàm phán các điều khoản tốt hơn.', 1),
  ('vocab_unit_c1_1_2', 'unit_c1_1', 'leverage', '/ˈlevərɪdʒ/', 'lợi thế, đòn bẩy', 'We have some leverage in this deal.', 'Chúng tôi có một số lợi thế trong thương vụ này.', 2),
  ('vocab_unit_c1_1_3', 'unit_c1_1', 'stakeholder', '/ˈsteɪkhoʊldər/', 'bên liên quan', 'All stakeholders must agree on the plan.', 'Tất cả các bên liên quan phải đồng ý với kế hoạch.', 3),
  ('vocab_unit_c1_1_4', 'unit_c1_1', 'revenue', '/ˈrevənuː/', 'doanh thu', 'Revenue increased by ten percent this quarter.', 'Doanh thu tăng mười phần trăm trong quý này.', 4),
  ('vocab_unit_c1_1_5', 'unit_c1_1', 'merger', '/ˈmɜːrdʒər/', 'sự sáp nhập', 'The merger was completed last year.', 'Việc sáp nhập đã hoàn tất vào năm ngoái.', 5),
  ('vocab_unit_c1_1_6', 'unit_c1_1', 'concession', '/kənˈseʃən/', 'sự nhượng bộ', 'Both sides made some concessions.', 'Cả hai bên đã có một số nhượng bộ.', 6),
  ('vocab_unit_c1_1_7', 'unit_c1_1', 'proposal', '/prəˈpoʊzəl/', 'đề xuất', 'They rejected our initial proposal.', 'Họ đã từ chối đề xuất ban đầu của chúng tôi.', 7),
  ('vocab_unit_c1_1_8', 'unit_c1_1', 'viable', '/ˈvaɪəbəl/', 'khả thi', 'Is this plan financially viable?', 'Kế hoạch này có khả thi về mặt tài chính không?', 8),
  ('vocab_unit_c1_2_1', 'unit_c1_2', 'hypothesis', '/haɪˈpɒθəsɪs/', 'giả thuyết', 'The hypothesis was not supported by the data.', 'Giả thuyết không được dữ liệu ủng hộ.', 1),
  ('vocab_unit_c1_2_2', 'unit_c1_2', 'methodology', '/ˌmeθəˈdɒlədʒi/', 'phương pháp luận', 'The study''s methodology has some limitations.', 'Phương pháp luận của nghiên cứu có một số hạn chế.', 2),
  ('vocab_unit_c1_2_3', 'unit_c1_2', 'correlation', '/ˌkɒrəˈleɪʃən/', 'mối tương quan', 'There is a strong correlation between the two factors.', 'Có mối tương quan mạnh giữa hai yếu tố.', 3),
  ('vocab_unit_c1_2_4', 'unit_c1_2', 'contradict', '/ˌkɒntrəˈdɪkt/', 'mâu thuẫn', 'This finding contradicts earlier research.', 'Phát hiện này mâu thuẫn với nghiên cứu trước đó.', 4),
  ('vocab_unit_c1_2_5', 'unit_c1_2', 'rigorous', '/ˈrɪɡərəs/', 'chặt chẽ, nghiêm ngặt', 'We need a more rigorous approach.', 'Chúng ta cần một cách tiếp cận chặt chẽ hơn.', 5),
  ('vocab_unit_c1_2_6', 'unit_c1_2', 'peer-reviewed', '/pɪr rɪˈvjuːd/', 'được bình duyệt', 'This is a peer-reviewed journal article.', 'Đây là một bài báo trên tạp chí được bình duyệt.', 6),
  ('vocab_unit_c1_2_7', 'unit_c1_2', 'implication', '/ˌɪmplɪˈkeɪʃən/', 'hàm ý, hệ quả', 'What are the implications of this study?', 'Hàm ý của nghiên cứu này là gì?', 7),
  ('vocab_unit_c1_2_8', 'unit_c1_2', 'empirical', '/ɪmˈpɪrɪkəl/', 'thực nghiệm', 'We need empirical evidence, not just theory.', 'Chúng ta cần bằng chứng thực nghiệm, không chỉ lý thuyết.', 8),
  ('vocab_unit_c1_3_1', 'unit_c1_3', 'break the ice', '/breɪk ði aɪs/', 'phá vỡ sự ngượng ngùng ban đầu', 'He told a joke to break the ice.', 'Anh ấy kể một câu chuyện cười để phá vỡ sự ngượng ngùng.', 1),
  ('vocab_unit_c1_3_2', 'unit_c1_3', 'on the fence', '/ɒn ðə fens/', 'lưỡng lự, chưa quyết định', 'I''m still on the fence about this decision.', 'Tôi vẫn còn lưỡng lự về quyết định này.', 2),
  ('vocab_unit_c1_3_3', 'unit_c1_3', 'cut corners', '/kʌt ˈkɔːrnərz/', 'làm ẩu để tiết kiệm', 'They cut corners to finish the project faster.', 'Họ làm ẩu để hoàn thành dự án nhanh hơn.', 3),
  ('vocab_unit_c1_3_4', 'unit_c1_3', 'get the ball rolling', '/ɡet ðə bɔːl ˈroʊlɪŋ/', 'bắt đầu khởi động việc gì', 'Let''s get the ball rolling on this project.', 'Hãy bắt đầu khởi động dự án này.', 4),
  ('vocab_unit_c1_3_5', 'unit_c1_3', 'under the weather', '/ˈʌndər ðə ˈweðər/', 'cảm thấy không khỏe', 'I''m feeling a bit under the weather today.', 'Hôm nay tôi cảm thấy hơi không khỏe.', 5),
  ('vocab_unit_c1_3_6', 'unit_c1_3', 'bite the bullet', '/baɪt ðə ˈbʊlɪt/', 'chấp nhận làm điều khó khăn', 'We just have to bite the bullet and finish it.', 'Chúng ta chỉ cần chấp nhận khó khăn và hoàn thành nó.', 6),
  ('vocab_unit_c1_3_7', 'unit_c1_3', 'in the long run', '/ɪn ðə lɔːŋ rʌn/', 'về lâu dài', 'This decision will pay off in the long run.', 'Quyết định này sẽ có lợi về lâu dài.', 7),
  ('vocab_unit_c1_3_8', 'unit_c1_3', 'read between the lines', '/riːd bɪˈtwiːn ðə laɪnz/', 'hiểu ý ngầm', 'You need to read between the lines here.', 'Bạn cần hiểu ý ngầm ở đây.', 8);

INSERT INTO content_unit_sentences (id, unit_id, english, vietnamese_hint, audio_tip, focus_grammar, sentence_order) VALUES
  ('sent_unit_a1_1_1', 'unit_a1_1', 'Hello, my name is Minh.', 'Xin chào, tên tôi là Minh.', 'Đọc chậm, rõ từng âm.', NULL, 1),
  ('sent_unit_a1_1_2', 'unit_a1_1', 'What is your name?', 'Tên bạn là gì?', 'Lên giọng nhẹ ở cuối câu hỏi.', NULL, 2),
  ('sent_unit_a1_1_3', 'unit_a1_1', 'I am from Vietnam.', 'Tôi đến từ Việt Nam.', NULL, 'I am from + tên quốc gia.', 3),
  ('sent_unit_a1_1_4', 'unit_a1_1', 'How old are you?', 'Bạn bao nhiêu tuổi?', NULL, NULL, 4),
  ('sent_unit_a1_1_5', 'unit_a1_1', 'Nice to meet you too.', 'Rất vui được gặp bạn.', NULL, NULL, 5),
  ('sent_unit_a1_1_6', 'unit_a1_1', 'This is my friend, Anna.', 'Đây là bạn tôi, Anna.', NULL, 'This is + tên để giới thiệu người khác.', 6),
  ('sent_unit_a1_2_1', 'unit_a1_2', 'I wake up at six o''clock every morning.', 'Tôi thức dậy lúc sáu giờ mỗi sáng.', NULL, 'Hiện tại đơn diễn tả thói quen.', 1),
  ('sent_unit_a1_2_2', 'unit_a1_2', 'What time do you have breakfast?', 'Bạn ăn sáng lúc mấy giờ?', NULL, NULL, 2),
  ('sent_unit_a1_2_3', 'unit_a1_2', 'I go to school by bus.', 'Tôi đi học bằng xe buýt.', NULL, 'by + phương tiện di chuyển.', 3),
  ('sent_unit_a1_2_4', 'unit_a1_2', 'She always does her homework in the evening.', 'Cô ấy luôn làm bài tập vào buổi tối.', NULL, 'Trạng từ tần suất always đứng trước động từ thường.', 4),
  ('sent_unit_a1_2_5', 'unit_a1_2', 'I never wake up late.', 'Tôi không bao giờ dậy muộn.', NULL, NULL, 5),
  ('sent_unit_a1_2_6', 'unit_a1_2', 'We usually have dinner at seven.', 'Chúng tôi thường ăn tối lúc bảy giờ.', NULL, NULL, 6),
  ('sent_unit_a1_3_1', 'unit_a1_3', 'I have two brothers and one sister.', 'Tôi có hai anh/em trai và một chị/em gái.', NULL, NULL, 1),
  ('sent_unit_a1_3_2', 'unit_a1_3', 'My family lives in Hanoi.', 'Gia đình tôi sống ở Hà Nội.', NULL, NULL, 2),
  ('sent_unit_a1_3_3', 'unit_a1_3', 'What is your phone number?', 'Số điện thoại của bạn là gì?', NULL, NULL, 3),
  ('sent_unit_a1_3_4', 'unit_a1_3', 'My father is fifty years old.', 'Bố tôi năm mươi tuổi.', NULL, NULL, 4),
  ('sent_unit_a1_3_5', 'unit_a1_3', 'Where do you live?', 'Bạn sống ở đâu?', NULL, NULL, 5),
  ('sent_unit_a1_3_6', 'unit_a1_3', 'This is a photo of my family.', 'Đây là ảnh gia đình tôi.', NULL, NULL, 6),
  ('sent_unit_a2_1_1', 'unit_a2_1', 'How much is this jacket?', 'Cái áo khoác này giá bao nhiêu?', NULL, NULL, 1),
  ('sent_unit_a2_1_2', 'unit_a2_1', 'Do you accept credit cards?', 'Bạn có nhận thẻ tín dụng không?', NULL, NULL, 2),
  ('sent_unit_a2_1_3', 'unit_a2_1', 'This is too expensive for me.', 'Cái này quá đắt với tôi.', NULL, 'too + tính từ.', 3),
  ('sent_unit_a2_1_4', 'unit_a2_1', 'Can I get a discount?', 'Tôi có thể được giảm giá không?', NULL, NULL, 4),
  ('sent_unit_a2_1_5', 'unit_a2_1', 'I''d like to try this on, please.', 'Tôi muốn thử cái này.', 'Nối I''d like to thành một cụm liền mạch.', NULL, 5),
  ('sent_unit_a2_1_6', 'unit_a2_1', 'Could I have a receipt, please?', 'Cho tôi xin hóa đơn được không?', NULL, NULL, 6),
  ('sent_unit_a2_2_1', 'unit_a2_2', 'I have a reservation under the name Nam.', 'Tôi đã đặt bàn dưới tên Nam.', NULL, NULL, 1),
  ('sent_unit_a2_2_2', 'unit_a2_2', 'What do you recommend?', 'Bạn gợi ý món gì?', NULL, NULL, 2),
  ('sent_unit_a2_2_3', 'unit_a2_2', 'This dish is too spicy for me.', 'Món này quá cay đối với tôi.', NULL, NULL, 3),
  ('sent_unit_a2_2_4', 'unit_a2_2', 'Could we get the bill, please?', 'Cho chúng tôi xin hóa đơn được không?', NULL, NULL, 4),
  ('sent_unit_a2_2_5', 'unit_a2_2', 'I''m allergic to seafood.', 'Tôi bị dị ứng hải sản.', NULL, 'be allergic to + danh từ.', 5),
  ('sent_unit_a2_2_6', 'unit_a2_2', 'The food here is really delicious.', 'Đồ ăn ở đây thực sự rất ngon.', NULL, NULL, 6),
  ('sent_unit_a2_3_1', 'unit_a2_3', 'Excuse me, how do I get to the train station?', 'Xin lỗi, làm sao để đến ga tàu?', NULL, NULL, 1),
  ('sent_unit_a2_3_2', 'unit_a2_3', 'Turn right at the next corner.', 'Rẽ phải ở góc đường tiếp theo.', NULL, 'Câu mệnh lệnh chỉ đường.', 2),
  ('sent_unit_a2_3_3', 'unit_a2_3', 'Is the museum far from here?', 'Bảo tàng có xa đây không?', NULL, NULL, 3),
  ('sent_unit_a2_3_4', 'unit_a2_3', 'I think I''m lost, can you help me?', 'Tôi nghĩ tôi bị lạc, bạn giúp tôi được không?', NULL, NULL, 4),
  ('sent_unit_a2_3_5', 'unit_a2_3', 'Go straight and then turn left.', 'Đi thẳng rồi rẽ trái.', NULL, NULL, 5),
  ('sent_unit_a2_3_6', 'unit_a2_3', 'It''s just a five-minute walk from here.', 'Chỉ mất năm phút đi bộ từ đây thôi.', NULL, NULL, 6),
  ('sent_unit_b1_1_1', 'unit_b1_1', 'I''m currently working on a new project.', 'Tôi hiện đang làm một dự án mới.', NULL, 'Hiện tại tiếp diễn cho hành động đang diễn ra.', 1),
  ('sent_unit_b1_1_2', 'unit_b1_1', 'Could we reschedule the meeting to Thursday?', 'Chúng ta có thể dời cuộc họp sang thứ Năm không?', NULL, NULL, 2),
  ('sent_unit_b1_1_3', 'unit_b1_1', 'I''ve gained a lot of experience in this field.', 'Tôi đã có được nhiều kinh nghiệm trong lĩnh vực này.', NULL, 'Hiện tại hoàn thành.', 3),
  ('sent_unit_b1_1_4', 'unit_b1_1', 'She was promoted after two years.', 'Cô ấy được thăng chức sau hai năm.', NULL, 'Câu bị động ở thì quá khứ.', 4),
  ('sent_unit_b1_1_5', 'unit_b1_1', 'I need to submit this assignment by Friday.', 'Tôi cần nộp bài tập này trước thứ Sáu.', NULL, NULL, 5),
  ('sent_unit_b1_1_6', 'unit_b1_1', 'What skills are required for this position?', 'Vị trí này yêu cầu những kỹ năng gì?', NULL, NULL, 6),
  ('sent_unit_b1_2_1', 'unit_b1_2', 'I''ve had a headache since this morning.', 'Tôi bị đau đầu từ sáng nay.', NULL, 'Hiện tại hoàn thành với since.', 1),
  ('sent_unit_b1_2_2', 'unit_b1_2', 'You should see a doctor about that.', 'Bạn nên đi khám bác sĩ về việc đó.', NULL, 'should + động từ nguyên mẫu để đưa lời khuyên.', 2),
  ('sent_unit_b1_2_3', 'unit_b1_2', 'I try to exercise every morning.', 'Tôi cố gắng tập thể dục mỗi sáng.', NULL, NULL, 3),
  ('sent_unit_b1_2_4', 'unit_b1_2', 'It took him a month to fully recover.', 'Anh ấy mất một tháng để hồi phục hoàn toàn.', NULL, 'It took + người + thời gian + to verb.', 4),
  ('sent_unit_b1_2_5', 'unit_b1_2', 'Could I make an appointment for next week?', 'Tôi có thể đặt hẹn cho tuần sau được không?', NULL, NULL, 5),
  ('sent_unit_b1_2_6', 'unit_b1_2', 'Eating a balanced diet keeps you healthy.', 'Ăn uống cân bằng giúp bạn khỏe mạnh.', NULL, NULL, 6),
  ('sent_unit_b1_3_1', 'unit_b1_3', 'Our flight has been delayed by two hours.', 'Chuyến bay của chúng tôi bị hoãn hai tiếng.', NULL, 'Hiện tại hoàn thành bị động.', 1),
  ('sent_unit_b1_3_2', 'unit_b1_3', 'Where do I check in my luggage?', 'Tôi ký gửi hành lý ở đâu?', NULL, NULL, 2),
  ('sent_unit_b1_3_3', 'unit_b1_3', 'Which platform does the train leave from?', 'Tàu khởi hành từ sân ga nào?', NULL, NULL, 3),
  ('sent_unit_b1_3_4', 'unit_b1_3', 'We still need to book our accommodation.', 'Chúng tôi vẫn cần đặt chỗ ở.', NULL, NULL, 4),
  ('sent_unit_b1_3_5', 'unit_b1_3', 'Do I need to transfer trains to get there?', 'Tôi có cần đổi tàu để đến đó không?', NULL, NULL, 5),
  ('sent_unit_b1_3_6', 'unit_b1_3', 'What''s our final destination on this trip?', 'Điểm đến cuối cùng của chuyến đi này là gì?', NULL, NULL, 6),
  ('sent_unit_b2_1_1', 'unit_b2_1', 'I see your point, but I have to disagree.', 'Tôi hiểu ý bạn, nhưng tôi phải không đồng ý.', NULL, NULL, 1),
  ('sent_unit_b2_1_2', 'unit_b2_1', 'There isn''t enough evidence to support that claim.', 'Không có đủ bằng chứng để ủng hộ tuyên bố đó.', NULL, NULL, 2),
  ('sent_unit_b2_1_3', 'unit_b2_1', 'From my perspective, the situation is more complicated.', 'Theo quan điểm của tôi, tình huống này phức tạp hơn.', NULL, 'Cụm mở đầu nêu quan điểm: From my perspective.', 3),
  ('sent_unit_b2_1_4', 'unit_b2_1', 'We should try to reach a compromise.', 'Chúng ta nên cố gắng đạt được một sự thỏa hiệp.', NULL, NULL, 4),
  ('sent_unit_b2_1_5', 'unit_b2_1', 'How do you justify such a decision?', 'Bạn biện minh cho quyết định đó như thế nào?', NULL, NULL, 5),
  ('sent_unit_b2_1_6', 'unit_b2_1', 'This is a highly controversial issue in society.', 'Đây là một vấn đề gây tranh cãi cao trong xã hội.', NULL, NULL, 6),
  ('sent_unit_b2_2_1', 'unit_b2_2', 'Artificial intelligence is transforming the way we work.', 'Trí tuệ nhân tạo đang thay đổi cách chúng ta làm việc.', NULL, NULL, 1),
  ('sent_unit_b2_2_2', 'unit_b2_2', 'I''m concerned about my privacy online.', 'Tôi lo ngại về quyền riêng tư của mình trên mạng.', NULL, 'be concerned about + danh từ.', 2),
  ('sent_unit_b2_2_3', 'unit_b2_2', 'Misinformation can spread faster than the truth.', 'Thông tin sai lệch có thể lan nhanh hơn sự thật.', NULL, NULL, 3),
  ('sent_unit_b2_2_4', 'unit_b2_2', 'Cybersecurity should be a priority for every company.', 'An ninh mạng nên là ưu tiên của mọi công ty.', NULL, NULL, 4),
  ('sent_unit_b2_2_5', 'unit_b2_2', 'We''ve become too dependent on our phones.', 'Chúng ta đã trở nên quá phụ thuộc vào điện thoại.', NULL, 'be dependent on + danh từ.', 5),
  ('sent_unit_b2_2_6', 'unit_b2_2', 'How does this algorithm decide what to show us?', 'Thuật toán này quyết định những gì để hiển thị cho chúng ta như thế nào?', NULL, NULL, 6),
  ('sent_unit_b2_3_1', 'unit_b2_3', 'We need to find more sustainable ways to live.', 'Chúng ta cần tìm những cách sống bền vững hơn.', NULL, NULL, 1),
  ('sent_unit_b2_3_2', 'unit_b2_3', 'Air pollution has gotten worse in recent years.', 'Ô nhiễm không khí đã trở nên tồi tệ hơn trong những năm gần đây.', NULL, 'Hiện tại hoàn thành diễn tả sự thay đổi theo thời gian.', 2),
  ('sent_unit_b2_3_3', 'unit_b2_3', 'The government should invest more in renewable energy.', 'Chính phủ nên đầu tư nhiều hơn vào năng lượng tái tạo.', NULL, NULL, 3),
  ('sent_unit_b2_3_4', 'unit_b2_3', 'This policy aims to reduce income inequality.', 'Chính sách này nhằm giảm bất bình đẳng thu nhập.', NULL, NULL, 4),
  ('sent_unit_b2_3_5', 'unit_b2_3', 'We should raise awareness about this issue.', 'Chúng ta nên nâng cao nhận thức về vấn đề này.', NULL, NULL, 5),
  ('sent_unit_b2_3_6', 'unit_b2_3', 'Plastic waste has a devastating impact on marine life.', 'Rác thải nhựa có tác động tàn phá đến sinh vật biển.', NULL, NULL, 6),
  ('sent_unit_c1_1_1', 'unit_c1_1', 'Let''s discuss the terms before we finalize the deal.', 'Hãy thảo luận các điều khoản trước khi chúng ta chốt thỏa thuận.', NULL, NULL, 1),
  ('sent_unit_c1_1_2', 'unit_c1_1', 'We''re willing to make a few concessions.', 'Chúng tôi sẵn sàng có một vài nhượng bộ.', NULL, 'be willing to + verb.', 2),
  ('sent_unit_c1_1_3', 'unit_c1_1', 'This proposal doesn''t seem financially viable.', 'Đề xuất này có vẻ không khả thi về mặt tài chính.', NULL, NULL, 3),
  ('sent_unit_c1_1_4', 'unit_c1_1', 'All stakeholders need to be on the same page.', 'Tất cả các bên liên quan cần thống nhất quan điểm.', NULL, 'Thành ngữ: be on the same page.', 4),
  ('sent_unit_c1_1_5', 'unit_c1_1', 'Our revenue has grown steadily over the past year.', 'Doanh thu của chúng tôi đã tăng trưởng ổn định trong năm qua.', NULL, 'Hiện tại hoàn thành với over the past year.', 5),
  ('sent_unit_c1_1_6', 'unit_c1_1', 'We have some leverage to negotiate a better price.', 'Chúng tôi có một số lợi thế để đàm phán mức giá tốt hơn.', NULL, NULL, 6),
  ('sent_unit_c1_2_1', 'unit_c1_2', 'Our hypothesis was not supported by the data.', 'Giả thuyết của chúng tôi không được dữ liệu ủng hộ.', NULL, 'Câu bị động thể quá khứ.', 1),
  ('sent_unit_c1_2_2', 'unit_c1_2', 'This finding contradicts what previous studies suggested.', 'Phát hiện này mâu thuẫn với những gì các nghiên cứu trước đây gợi ý.', NULL, NULL, 2),
  ('sent_unit_c1_2_3', 'unit_c1_2', 'We need a more rigorous methodology for this research.', 'Chúng ta cần một phương pháp luận chặt chẽ hơn cho nghiên cứu này.', NULL, NULL, 3),
  ('sent_unit_c1_2_4', 'unit_c1_2', 'What are the broader implications of these results?', 'Hàm ý rộng hơn của những kết quả này là gì?', NULL, NULL, 4),
  ('sent_unit_c1_2_5', 'unit_c1_2', 'The two variables show a strong correlation.', 'Hai biến số này cho thấy mối tương quan mạnh.', NULL, NULL, 5),
  ('sent_unit_c1_2_6', 'unit_c1_2', 'This claim needs to be backed by empirical evidence.', 'Tuyên bố này cần được hỗ trợ bởi bằng chứng thực nghiệm.', NULL, 'Câu bị động với need to be + past participle.', 6),
  ('sent_unit_c1_3_1', 'unit_c1_3', 'Let''s get the ball rolling on this new project.', 'Hãy bắt đầu khởi động dự án mới này.', NULL, 'Thành ngữ: get the ball rolling.', 1),
  ('sent_unit_c1_3_2', 'unit_c1_3', 'I''m still on the fence about whether to accept the offer.', 'Tôi vẫn còn lưỡng lự về việc có nên nhận lời đề nghị không.', NULL, 'Thành ngữ: on the fence.', 2),
  ('sent_unit_c1_3_3', 'unit_c1_3', 'We shouldn''t cut corners just to save time.', 'Chúng ta không nên làm ẩu chỉ để tiết kiệm thời gian.', NULL, 'Thành ngữ: cut corners.', 3),
  ('sent_unit_c1_3_4', 'unit_c1_3', 'I''m feeling a bit under the weather today.', 'Hôm nay tôi cảm thấy hơi không khỏe.', NULL, 'Thành ngữ: under the weather.', 4),
  ('sent_unit_c1_3_5', 'unit_c1_3', 'Sometimes you just have to bite the bullet and move on.', 'Đôi khi bạn chỉ cần chấp nhận khó khăn và tiến lên.', NULL, 'Thành ngữ: bite the bullet.', 5),
  ('sent_unit_c1_3_6', 'unit_c1_3', 'This investment will pay off in the long run.', 'Khoản đầu tư này sẽ mang lại lợi ích về lâu dài.', NULL, 'Thành ngữ: in the long run.', 6);
